
server.port: 8986

    datasource:
        url: jdbc:mysql://localhost:3306/finalWork?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: admin
        driver: com.mysql.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect  #org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true

        properties:
            hibernate.hbm2ddl.auto: create
            hibernate.show_sql: true
            hibernate.format_sql: true

            hibernate.id.new_generator_mappings: false
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.envers.audit_table_suffix: _aud
            hibernate.envers.default_schema: audit
            org.hibernate.envers.store_data_at_delete: true
#            spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


 spring.jpa.properties.org.hibernate.envers.audit_table_suffix: _AUD
 spring.jpa.properties.org.hibernate.envers.revision_field_name: REVISION_ID
 spring.jpa.properties.org.hibernate.envers.revision_type_field_name: REVISION_TYPE


#spring.jpa.properties.org.hibernate.envers.default_schema: app_audit

#spring.freemarker.checkTemplateLocation: false


#hibernate.cache.use_second_level_cache: false
